package com.java.assessment.JAVA_ASSESSMENT.constant;

public class MessageConstants {
    private MessageConstants() {}

    public static final String OTP_GENERATION_MESSAGE = "OTP_GENERATION_MESSAGE";

    public static final String OTP_VERIFICATION_MESSAGE = "OTP_VERIFICATION_MESSAGE";

    public static final String EMAIL_SEND_SUCCESSFULLY_MESSAGE = "EMAIL_SEND_SUCCESSFULLY_MESSAGE";

    public static final String VISIT_URL_SETTING_NEW_PASSWORD = "VISIT_URL_SETTING_NEW_PASSWORD";

    public static final String PASSWORD_RESET_SUCCESSFULLY = "PASSWORD_RESET_SUCCESSFULLY";

    public static final String VEHICLE_SAVED_SUCCESSFULLY = "VEHICLE_SAVED_SUCCESSFULLY";

    public static final String VEHICLE_UPDATED_SUCCESSFULLY = "VEHICLE_UPDATED_SUCCESSFULLY";

    public static final String VEHICLES_FETCHED_SUCCESSFULLY = "VEHICLES_FETCHED_SUCCESSFULLY";

    public static final String VEHICLE_BY_ID_FETCHED_SUCCESSFULLY = "VEHICLE_BY_ID_FETCHED_SUCCESSFULLY";

    public static final String VEHICLE_BY_ID_DELETED_SUCCESSFULLY = "VEHICLE_BY_ID_DELETED_SUCCESSFULLY";

    public static final String USER_WITH_USERNAME_LOGGED_IN_SUCCESSFULLY = "USER_WITH_USERNAME_LOGGED_IN_SUCCESSFULLY";

    public static final String EXPENSE_SAVED_SUCCESSFULLY = "EXPENSE_SAVED_SUCCESSFULLY";

    public static final String EXPENSE_UPDATED_SUCCESSFULLY = "EXPENSE_UPDATED_SUCCESSFULLY";

    public static final String EXPENSES_FETCHED_SUCCESSFULLY = "EXPENSES_FETCHED_SUCCESSFULLY";

    public static final String EXPENSE_DELETED_SUCCESSFULLY = "EXPENSE_DELETED_SUCCESSFULLY";

    public static final String VEHICLE_BRAND_FETCHED_SUCCESSFULLY = "VEHICLE_BRAND_FETCHED_SUCCESSFULLY";
}
